spring:
  application:
    name: Borsibaar
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  sql:
    init:
      mode: never

server:
  forward-headers-strategy: framework

jwt:
  secret: ${JWT_SECRET}

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}
  frontend:
    url: ${APP_FRONTEND_URL:http://localhost:3000}

logging:
  level:
    org.springframework.security: DEBUG
    com.borsibaar: DEBUG